# Generated by Django 3.2.8 on 2021-10-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackboxitem',
            name='black_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculator.blackbox'),
        ),
        migrations.AlterField(
            model_name='blackboxitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculator.product'),
        ),
    ]
