# Generated by Django 3.2.8 on 2021-10-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20211018_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackboxitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='blackboxitem',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
