# Generated by Django 3.2.8 on 2021-10-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20211022_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackbox',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
