# Generated by Django 3.2.8 on 2021-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_blackbox_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blackbox',
            options={'ordering': ('price',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',)},
        ),
        migrations.RemoveField(
            model_name='blackbox',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_created',
        ),
        migrations.AddField(
            model_name='blackbox',
            name='loyalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blackbox',
            name='rentability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
