# Generated by Django 3.2.8 on 2021-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20211029_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackbox',
            name='loyalty',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='blackbox',
            name='rentability',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
