# Generated by Django 3.2.8 on 2021-11-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_lottery_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lottery_items', to='calculator.product'),
        ),
    ]
